/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-03-22 04:24:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fashion.common.Formatter;
import com.fashion.model.domain.Cart;
import com.fashion.model.repository.CartDAO;
import com.fashion.model.domain.Customer;
import java.util.List;
import com.fashion.model.domain.Topcategory;
import com.fashion.model.repository.TopcategoryDAO;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

CartDAO cartDAO=new CartDAO(); 

	TopcategoryDAO topDAO=new TopcategoryDAO();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/inc/userinfo.jsp", Long.valueOf(1553059206918L));
    _jspx_dependants.put("/inc/sidebar.jsp", Long.valueOf(1553048074968L));
    _jspx_dependants.put("/inc/header.jsp", Long.valueOf(1552957629537L));
    _jspx_dependants.put("/inc/head.jsp", Long.valueOf(1552959256123L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.fashion.common.Formatter");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashion.model.domain.Customer");
    _jspx_imports_classes.add("com.fashion.model.repository.TopcategoryDAO");
    _jspx_imports_classes.add("com.fashion.model.repository.CartDAO");
    _jspx_imports_classes.add("com.fashion.model.domain.Cart");
    _jspx_imports_classes.add("com.fashion.model.domain.Topcategory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	Customer cs=(Customer)session.getAttribute("customer");
	List<Cart> cartList=cartDAO.selectByCustomer(cs.getCustomer_id());

      out.write('\r');
      out.write('\n');
      out.write('\n');

	String topcategory_id=request.getParameter("topcategory_id");
	//out.print("넘겨받은 상위 카테고리의 id값은 "+topcategory_id);
	
	//파라미터가 넘어오면, subcategory_id 값을 대체하자!!
	int subcategory_id=1;//기본값..
	if(request.getParameter("subcategory_id")!=null){//넘어오면...
		subcategory_id=Integer.parseInt(request.getParameter("subcategory_id"));
	}

      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\n");
      out.write("<title>FashionShop</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\" content=\"aStar Fashion Template Project\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap-4.1.3/bootstrap.css\">\n");
      out.write("<link href=\"plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/categories.css\">\n");
      out.write("<script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/popper.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n");
      out.write("<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n");
      out.write("<script src=\"plugins/easing/easing.js\"></script>\n");
      out.write("<script src=\"plugins/parallax-js-master/parallax.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/isotope.pkgd.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/fitcolumns.js\"></script>\n");
      out.write("<script src=\"js/product.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/cart.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/cart_responsive.css\">\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function delCart(){\r\n");
      out.write("\t//checkbox를 체크했는지 검증\r\n");
      out.write("\tvar arr=$(\"input[type='checkbox']\");\r\n");
      out.write("\tvar count=0;\r\n");
      out.write("\tfor(var i=0;i<arr.length;i++){\r\n");
      out.write("\t\tif($(arr[i]).is(\":checked\")){\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(count<=0){\r\n");
      out.write("\t\talert(\"삭제할 상품을 선택하십시오\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(confirm(\"정말 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t$(\"#cart-form\").attr({\r\n");
      out.write("\t\t\t\"method\":\"post\",\r\n");
      out.write("\t\t\t\"action\":\"del_cart.jsp\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#cart-form\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//장바구니 안의 모든 체크박스의 상태를 일괄 적용\r\n");
      out.write("function checkAll(obj){\r\n");
      out.write("\tfor(var i=0;i<$(\"input[name='cart_id']\").length;i++){\r\n");
      out.write("\t\t$($(\"input[name='cart_id']\")[i]).attr(\"checked\", obj.checked);\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function payform(){\r\n");
      out.write("\t$(\"#cart-form\").attr({\r\n");
      out.write("\t\t\"method\":\"post\",\r\n");
      out.write("\t\t\"action\":\"payment.jsp\"\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#cart-form\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//장바구니 정보 변경\r\n");
      out.write("function updateCart(){\r\n");
      out.write("\tvar len=$(\"span[name='span_ea']\").length;\r\n");
      out.write("\tfor(var i=0;i<len;i++){\r\n");
      out.write("\t\tvar n=$($(\"span[name='span_ea']\")[i]).text();\r\n");
      out.write("\t\t$($(\"input[name='ea']\")[i]).val(n);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm(\"장바구니를 수정하시겠습니까?\")){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#cart-form\").attr({\r\n");
      out.write("\t\t\"action\":\"cart_edit.jsp\",\r\n");
      out.write("\t\t\"method\":\"post\"\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#cart-form\").submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"super_container\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\r\n");
      out.write("\t<header class=\"header\">\r\n");
      out.write("\t\t<div class=\"header_content d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Hamburger -->\r\n");
      out.write("\t\t\t<div class=\"hamburger menu_mm\"><i class=\"fa fa-bars menu_mm\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t<div class=\"header_logo\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><div>a<span>star</span></div></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t<nav class=\"header_nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\">home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">woman</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">man</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">lookbook</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header Extra -->\r\n");
      out.write("\t\t\t<div class=\"header_extra ml-auto d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Language -->\r\n");
      out.write("\t\t\t\t<div class=\"info_languages has_children\">\r\n");
      out.write("\t\t\t\t\t<div class=\"language_flag\"><img src=\"images/flag_1.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">english</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Language Dropdown Menu -->\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_2.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">french</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_3.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">japanese</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_4.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">russian</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_5.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">spanish</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Currency -->\r\n");
      out.write("\t\t\t\t<div class=\"info_currencies has_children\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">usd</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Currencies Dropdown Menu -->\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Cart -->\r\n");
      out.write("\t\t\t\t<div class=\"cart d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cart_icon\"><a href=\"cart.html\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/bag.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cart_num\">2</div>\r\n");
      out.write("\t\t\t\t\t</a></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"menu d-flex flex-column align-items-start justify-content-start menu_mm trans_400\">\r\n");
      out.write("\t\t<div class=\"menu_close_container\"><div class=\"menu_close\"><div></div><div></div></div></div>\r\n");
      out.write("\t\t<div class=\"menu_top d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Language -->\r\n");
      out.write("\t\t\t<div class=\"info_languages has_children\">\r\n");
      out.write("\t\t\t\t<div class=\"language_flag\"><img src=\"images/flag_1.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_text\">english</div>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Language Dropdown Menu -->\r\n");
      out.write("\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_2.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">french</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_3.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">japanese</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_4.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">russian</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_5.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">spanish</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Currency -->\r\n");
      out.write("\t\t\t<div class=\"info_currencies has_children\">\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_text\">usd</div>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Currencies Dropdown Menu -->\r\n");
      out.write("\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\r\n");
      out.write("\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"menu_search\">\r\n");
      out.write("\t\t\t<form action=\"#\" class=\"header_search_form menu_mm\">\r\n");
      out.write("\t\t\t\t<input type=\"search\" class=\"search_input menu_mm\" placeholder=\"Search\" required=\"required\">\r\n");
      out.write("\t\t\t\t<button class=\"header_search_button d-flex flex-column align-items-center justify-content-center menu_mm\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-search menu_mm\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav class=\"menu_nav\">\r\n");
      out.write("\t\t\t<ul class=\"menu_mm\">\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"index.html\">home</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">woman</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">man</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">lookbook</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"blog.html\">blog</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"contact.html\">contact</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"menu_extra\">\r\n");
      out.write("\t\t\t<div class=\"menu_social\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Info -->\r\n");
      out.write("\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t<div class=\"info_content d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	if (session.getAttribute("customer") != null) {

      out.write('\r');
      out.write('\n');

	Customer customer = (Customer) session.getAttribute("customer");

      out.write("\r\n");
      out.write("<div class=\"info_languages has_children\">\r\n");
      out.write("\t<div class=\"language_flag\"></div>\r\n");
      out.write("\t<div class=\"dropdown_text\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.print(customer.getName());
      out.write("님\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dropdown_arrow\">\r\n");
      out.write("\t\t<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">MyPage</div>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/member/logout.jsp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">Logout</div>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Currency -->\r\n");
      out.write("\t\t\t\t<div class=\"info_currencies has_children\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">usd</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Currencies Dropdown Menu -->\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Logo -->\r\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	List<Topcategory> topList=topDAO.selectAll();

      out.write("\n");
      out.write("<div class=\"sidebar_logo\">\n");
      out.write("\t<a href=\"/\"><div>a<span>Shop</span></div></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<nav class=\"sidebar_nav\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"index.jsp\">home<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t");
for(int i=0;i<topList.size();i++){
      out.write('\n');
      out.write('	');
      out.write('	');
Topcategory topcategory=topList.get(i); 
      out.write("\n");
      out.write("\t\t<li><a href=\"/category.jsp?topcategory_id=");
      out.print(topcategory.getTopcategory_id());
      out.write('"');
      out.write('>');
      out.print(topcategory.getTop_name());
      out.write("<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t");
}
      out.write("\n");
      out.write("\t\t<li><a href=\"#\">contact<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t<li><a href=\"/registForm.jsp\">Join us<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t</ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\t\t<!-- Search -->\r\n");
      out.write("\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t<form action=\"#\" class=\"search_form\" id=\"sidebar_search_form\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"search_input\" placeholder=\"Search\" required=\"required\">\r\n");
      out.write("\t\t\t\t<button class=\"search_button\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Cart -->\r\n");
      out.write("\t\t<div class=\"cart d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t<div class=\"cart_icon\"><a href=\"cart.html\">\r\n");
      out.write("\t\t\t\t<img src=\"images/bag.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"cart_num\">2</div>\r\n");
      out.write("\t\t\t</a></div>\r\n");
      out.write("\t\t\t<div class=\"cart_text\">bag</div>\r\n");
      out.write("\t\t\t<div class=\"cart_price\">$39.99 (1)</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Home -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"home\">\r\n");
      out.write("\t\t<div class=\"parallax_background parallax-window\" data-parallax=\"scroll\" data-image-src=\"images/product_background.jpg\" data-speed=\"0.8\"></div>\r\n");
      out.write("\t\t<div class=\"home_container\">\r\n");
      out.write("\t\t\t<div class=\"home_content\">\r\n");
      out.write("\t\t\t\t<div class=\"home_title\">Cart</div>\r\n");
      out.write("\t\t\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>Your Cart</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Cart -->\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"cart-form\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"topcategory_id\" value=\"");
      out.print(topcategory_id);
      out.write("\" />\r\n");
      out.write("\t<div class=\"cart_section\">\r\n");
      out.write("\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cart_container\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Cart Bar -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cart_bar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" onClick=\"checkAll(this)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"cart_bar_list item_list d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Product</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Color</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Size</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Price</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Quantity</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Total</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Cart Items -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cart_items\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"cart_items_list\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Cart Item -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										int total=0;
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
for(int i=0;i<cartList.size();i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
Cart cart=cartList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
total+=cart.getProduct().getPrice()*cart.getEa(); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"product_name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" style=\"width:50px;\" name=\"cart_id\" value=\"");
      out.print(cart.getCart_id() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div><div class=\"product_image\"><img src=\"/data/");
      out.print(cart.getProduct().getFilename() );
      out.write("\" alt=\"\"></div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"product_name\"><a href=\"product.html\">");
      out.print(cart.getProduct().getProduct_name() );
      out.write("</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_color text-lg-center product_text\"><span>Color: </span>Brown</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_size text-lg-center product_text\"><span>Size: </span>One Size</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price text-lg-center product_text\"><span>Price: </span>");
      out.print(Formatter.getCurrency(cart.getProduct().getPrice()));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_quantity_container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"product_quantity ml-lg-auto mr-lg-auto text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span name=\"span_ea\" class=\"product_text product_num\">");
      out.print(cart.getEa() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"qty_sub qty_button trans_200 text-center\"><span>-</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"qty_add qty_button trans_200 text-center\"><span>+</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_total text-lg-center product_text\"><span>Total: </span>");
      out.print(Formatter.getCurrency(cart.getProduct().getPrice()*cart.getEa()) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" size=\"3\" name=\"product_id\" value=\"");
      out.print(cart.getProduct().getProduct_id() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" size=\"3\" name=\"ea\" value=\"");
      out.print(cart.getEa() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Cart Buttons -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cart_buttons d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart_buttons_inner ml-auto d-flex flex-row align-items-start justify-content-start flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"button button_continue trans_200\"><a href=\"categories.html\">continue shopping</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"button button_clear trans_200\"><a href=\"javascript:delCart()\">장바구니 삭제</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"button button_update trans_200\"><a href=\"javascript:updateCart()\">update cart</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"total\" value=\"");
      out.print(total	);
      out.write("\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"section_container cart_extra_container\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Shipping & Delivery -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xxl-6\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Cart Total -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xxl-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cart_extra cart_extra_2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cart_extra_content cart_extra_total\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart_extra_title\">Cart Total</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"cart_extra_total_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_title\">Subtotal</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_value ml-auto\">");
      out.print(Formatter.getCurrency(total) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_title\">Shipping</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_value ml-auto\">Free</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_title\">Total</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_value ml-auto\">");
      out.print(Formatter.getCurrency(total) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"checkout_button trans_200\"><a href=\"javascript:payform()\">결제하기</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Newsletter -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"newsletter\">\r\n");
      out.write("\t\t<div class=\"parallax_background parallax-window\" data-parallax=\"scroll\" data-image-src=\"images/newsletter.jpg\" data-speed=\"0.8\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 offset-lg-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"newsletter_content text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"newsletter_title_container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsletter_title\">subscribe to our newsletter</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsletter_subtitle\">we won't spam, we promise!</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"newsletter_form_container\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" id=\"newsletter_form\" class=\"newsletter_form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" class=\"newsletter_input\" placeholder=\"your e-mail here\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"newsletter_button\">submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer_content\">\r\n");
      out.write("\t\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- About -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_about\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><div>a<span>star</span></div></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_about_text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam fringilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cards\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_3.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_5.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Questions -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_questions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">questions</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Track Orders</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Returns</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Shipping</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Partners</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Bloggers</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Support</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Press</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Blog -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_blog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">blog</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_blog_container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Blog Item -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_item d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_image\"><a href=\"blog.html\"><img src=\"images/footer_blog_1.jpg\" alt=\"\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_title\"><a href=\"blog.html\">what shoes to wear</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_date\">june 06, 2018</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_link\"><a href=\"blog.html\">Read More</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Blog Item -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_item d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_image\"><a href=\"blog.html\"><img src=\"images/footer_blog_2.jpg\" alt=\"\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_title\"><a href=\"blog.html\">trends this year</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_date\">june 06, 2018</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_link\"><a href=\"blog.html\">Read More</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Contact -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">contact</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_contact_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>C.</span><div>Your Company Ltd</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>A.</span><div>1481 Creekside Lane  Avila Beach, CA 93424, P.O. BOX 68</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>T.</span><div>+53 345 7953 32453</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>E.</span><div>office@youremail.com</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Social -->\r\n");
      out.write("\t\t<div class=\"footer_social\">\r\n");
      out.write("\t\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_social_container d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Instagram -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">instagram</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Google + -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">google +</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Pinterest -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">pinterest</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Facebook -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">facebook</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Twitter -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">twitter</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- YouTube -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-youtube\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">youtube</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Tumblr -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-tumblr-square\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">tumblr</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Credits -->\r\n");
      out.write("\t\t<div class=\"credits\">\r\n");
      out.write("\t\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"credits_content d-flex flex-row align-items-center justify-content-end\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"credits_text\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"js/cart.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
