/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-03-20 05:21:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.fashion.model.domain.Customer;
import java.util.List;
import com.fashion.model.domain.Topcategory;
import com.fashion.model.repository.TopcategoryDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	TopcategoryDAO topDAO=new TopcategoryDAO();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/inc/userinfo.jsp", Long.valueOf(1553059206918L));
    _jspx_dependants.put("/inc/sidebar.jsp", Long.valueOf(1553048074968L));
    _jspx_dependants.put("/inc/head.jsp", Long.valueOf(1552959256123L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashion.model.domain.Customer");
    _jspx_imports_classes.add("com.fashion.model.repository.TopcategoryDAO");
    _jspx_imports_classes.add("com.fashion.model.domain.Topcategory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title>FashionShop</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\" content=\"aStar Fashion Template Project\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap-4.1.3/bootstrap.css\">\n");
      out.write("<link href=\"plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/categories.css\">\n");
      out.write("<script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/popper.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n");
      out.write("<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n");
      out.write("<script src=\"plugins/easing/easing.js\"></script>\n");
      out.write("<script src=\"plugins/parallax-js-master/parallax.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/isotope.pkgd.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/fitcolumns.js\"></script>\n");
      out.write("<script src=\"js/product.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"super_container\">\n");
      out.write("\n");
      out.write("\t<!-- Header -->\n");
      out.write("\n");
      out.write("\t<header class=\"header\">\n");
      out.write("\t\t<div class=\"header_content d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Hamburger -->\n");
      out.write("\t\t\t<div class=\"hamburger menu_mm\"><i class=\"fa fa-bars menu_mm\" aria-hidden=\"true\"></i></div>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t<div class=\"header_logo\">\n");
      out.write("\t\t\t\t<a href=\"#\"><div>a<span>star</span></div></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Navigation -->\n");
      out.write("\t\t\t<nav class=\"header_nav\">\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\">home</a></li>\n");
      out.write("\t\t\t\t\t");
for(int i=0;i<4;i++){
      out.write("\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">woman");
      out.print(i);
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">고객센터</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Header Extra -->\n");
      out.write("\t\t\t<div class=\"header_extra ml-auto d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Language -->\n");
      out.write("\t\t\t\t<div class=\"info_languages has_children\">\n");
      out.write("\t\t\t\t\t<div class=\"language_flag\"><img src=\"images/flag_1.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">english</div>\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Language Dropdown Menu -->\n");
      out.write("\t\t\t\t\t <ul>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_2.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">french</div>\n");
      out.write("\t\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_3.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">japanese</div>\n");
      out.write("\t\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_4.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">russian</div>\n");
      out.write("\t\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_5.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">spanish</div>\n");
      out.write("\t\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t\t </ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Currency -->\n");
      out.write("\t\t\t\t<div class=\"info_currencies has_children\">\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">usd</div>\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Currencies Dropdown Menu -->\n");
      out.write("\t\t\t\t\t <ul>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\n");
      out.write("\t\t\t\t\t </ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Cart -->\n");
      out.write("\t\t\t\t<div class=\"cart d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t<div class=\"cart_icon\"><a href=\"cart.html\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/bag.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t<div class=\"cart_num\">2</div>\n");
      out.write("\t\t\t\t\t</a></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\t<!-- Menu -->\n");
      out.write("\n");
      out.write("\t<div class=\"menu d-flex flex-column align-items-start justify-content-start menu_mm trans_400\">\n");
      out.write("\t\t<div class=\"menu_close_container\"><div class=\"menu_close\"><div></div><div></div></div></div>\n");
      out.write("\t\t<div class=\"menu_top d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Language -->\n");
      out.write("\t\t\t<div class=\"info_languages has_children\">\n");
      out.write("\t\t\t\t<div class=\"language_flag\"><img src=\"images/flag_1.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t<div class=\"dropdown_text\">english</div>\n");
      out.write("\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- Language Dropdown Menu -->\n");
      out.write("\t\t\t\t <ul>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_2.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">french</div>\n");
      out.write("\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_3.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">japanese</div>\n");
      out.write("\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_4.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">russian</div>\n");
      out.write("\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_5.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">spanish</div>\n");
      out.write("\t\t\t\t \t</a></li>\n");
      out.write("\t\t\t\t </ul>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Currency -->\n");
      out.write("\t\t\t<div class=\"info_currencies has_children\">\n");
      out.write("\t\t\t\t<div class=\"dropdown_text\">usd</div>\n");
      out.write("\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Currencies Dropdown Menu -->\n");
      out.write("\t\t\t\t <ul>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\n");
      out.write("\t\t\t\t </ul>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"menu_search\">\n");
      out.write("\t\t\t<form action=\"#\" class=\"header_search_form menu_mm\">\n");
      out.write("\t\t\t\t<input type=\"search\" class=\"search_input menu_mm\" placeholder=\"Search\" required=\"required\">\n");
      out.write("\t\t\t\t<button class=\"header_search_button d-flex flex-column align-items-center justify-content-center menu_mm\">\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-search menu_mm\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<nav class=\"menu_nav\">\n");
      out.write("\t\t\t<ul class=\"menu_mm\">\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"index.html\">home</a></li>\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">woman</a></li>\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">man</a></li>\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">lookbook</a></li>\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"blog.html\">blog</a></li>\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"contact.html\">contact</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<div class=\"menu_extra\">\n");
      out.write("\t\t\t<div class=\"menu_social\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- Sidebar -->\n");
      out.write("\n");
      out.write("\t<div class=\"sidebar\">\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Info -->\n");
      out.write("\t\t<div class=\"info\">\n");
      out.write("\t\t\t<div class=\"info_content d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	if (session.getAttribute("customer") != null) {

      out.write('\r');
      out.write('\n');

	Customer customer = (Customer) session.getAttribute("customer");

      out.write("\r\n");
      out.write("<div class=\"info_languages has_children\">\r\n");
      out.write("\t<div class=\"language_flag\"></div>\r\n");
      out.write("\t<div class=\"dropdown_text\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.print(customer.getName());
      out.write("님\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dropdown_arrow\">\r\n");
      out.write("\t\t<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">MyPage</div>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/member/logout.jsp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">Logout</div>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	}

      out.write("\n");
      out.write("\t\t\t\t<!-- Currency -->\n");
      out.write("\t\t\t\t<div class=\"info_currencies has_children\">\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">usd</div>\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Currencies Dropdown Menu -->\n");
      out.write("\t\t\t\t\t <ul>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\n");
      out.write("\t\t\t\t\t </ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Logo -->\n");
      out.write("\n");
      out.write("\t\t<!-- Sidebar Navigation -->\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	List<Topcategory> topList=topDAO.selectAll();

      out.write("\n");
      out.write("<div class=\"sidebar_logo\">\n");
      out.write("\t<a href=\"/\"><div>a<span>Shop</span></div></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<nav class=\"sidebar_nav\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"index.jsp\">home<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t");
for(int i=0;i<topList.size();i++){
      out.write('\n');
      out.write('	');
      out.write('	');
Topcategory topcategory=topList.get(i); 
      out.write("\n");
      out.write("\t\t<li><a href=\"/category.jsp?topcategory_id=");
      out.print(topcategory.getTopcategory_id());
      out.write('"');
      out.write('>');
      out.print(topcategory.getTop_name());
      out.write("<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t");
}
      out.write("\n");
      out.write("\t\t<li><a href=\"#\">contact<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t<li><a href=\"/registForm.jsp\">Join us<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t</ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Search -->\n");
      out.write("\t\t<div class=\"search\">\n");
      out.write("\t\t\t<form action=\"#\" class=\"search_form\" id=\"sidebar_search_form\">\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"search_input\" placeholder=\"Search\" required=\"required\">\n");
      out.write("\t\t\t\t<button class=\"search_button\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Cart -->\n");
      out.write("\t\t<div class=\"cart d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t<div class=\"cart_icon\"><a href=\"cart.html\">\n");
      out.write("\t\t\t\t<img src=\"images/bag.png\" alt=\"\">\n");
      out.write("\t\t\t\t<div class=\"cart_num\">2</div>\n");
      out.write("\t\t\t</a></div>\n");
      out.write("\t\t\t<div class=\"cart_text\">bag</div>\n");
      out.write("\t\t\t<div class=\"cart_price\">$39.99 (1)</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Home -->\n");
      out.write("\n");
      out.write("\t<div class=\"home\">\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Home Slider -->\n");
      out.write("\t\t<div class=\"home_slider_container\">\n");
      out.write("\t\t\t<div class=\"owl-carousel owl-theme home_slider\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- Slide -->\n");
      out.write("\t\t\t\t<div class=\"owl-item\">\n");
      out.write("\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(images/home_slider_1.jpg)\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"home_content_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home_content\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_discount d-flex flex-row align-items-end justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_discount_num\">20</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_discount_text\">Discount on the</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_title\">New Collection</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"button button_1 home_button trans_200\"><a href=\"categories.html\">Shop NOW!</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Slide -->\n");
      out.write("\t\t\t\t<div class=\"owl-item\">\n");
      out.write("\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(images/home_slider_1.jpg)\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"home_content_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home_content\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_discount d-flex flex-row align-items-end justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_discount_num\">20</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_discount_text\">Discount on the</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_title\">New Collection</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"button button_1 home_button trans_200\"><a href=\"categories.html\">Shop NOW!</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Slide -->\n");
      out.write("\t\t\t\t<div class=\"owl-item\">\n");
      out.write("\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(images/home_slider_1.jpg)\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"home_content_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home_content\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_discount d-flex flex-row align-items-end justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_discount_num\">20</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_discount_text\">Discount on the</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_title\">New Collection</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"button button_1 home_button trans_200\"><a href=\"categories.html\">Shop NOW!</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t<!-- Home Slider Navigation -->\n");
      out.write("\t\t\t<div class=\"home_slider_nav home_slider_prev trans_200\"><div class=\" d-flex flex-column align-items-center justify-content-center\"><img src=\"images/prev.png\" alt=\"\"></div></div>\n");
      out.write("\t\t\t<div class=\"home_slider_nav home_slider_next trans_200\"><div class=\" d-flex flex-column align-items-center justify-content-center\"><img src=\"images/next.png\" alt=\"\"></div></div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Boxes -->\n");
      out.write("\t\n");
      out.write("\t<div class=\"boxes\">\n");
      out.write("\t\t<div class=\"section_container\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Box -->\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 box_col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_image\"><img src=\"images/box_1.jpg\" alt=\"\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_title trans_200\"><a href=\"categories.html\">summer collection</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Box -->\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 box_col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_image\"><img src=\"images/box_2.jpg\" alt=\"\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_title trans_200\"><a href=\"categories.html\">eyewear collection</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Box -->\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 box_col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_image\"><img src=\"images/box_3.jpg\" alt=\"\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_title trans_200\"><a href=\"categories.html\">basic pieces</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Categories -->\n");
      out.write("\n");
      out.write("\t<div class=\"categories\">\n");
      out.write("\t\t<div class=\"section_container\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col text-center\">\n");
      out.write("\t\t\t\t\t\t<div class=\"categories_list_container\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"categories_list d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"categories.html\">new arrivals</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"categories.html\">recommended</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"categories.html\">best sellers</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Products -->\n");
      out.write("\n");
      out.write("\t<div class=\"products\">\n");
      out.write("\t\t<div class=\"section_container\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"products_container grid\">\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item hot\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_1.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_tag\">hot</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">long red shirt</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$39.90</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\"><img src=\"images/product_2.jpg\" alt=\"\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">hype grey shirt</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$19.50</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item sale\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_3.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_tag\">sale</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">long sleeve jacket</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$32.20<span>RRP 64.40</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_4.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">denim men shirt</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$59.90</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_5.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">long red shirt</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$79.90</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item new\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_6.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_tag\">new</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">hype grey shirt</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$59.90</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_7.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">long sleeve jacket</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$15.90</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Product -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product grid-item sale\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product_8.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_tag\">sale</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_title\"><a href=\"product.html\">denim men shirt</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_price\">$43.99<span>RRP 64.40</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_button ml-auto mr-auto trans_200\"><a href=\"#\">add to cart</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Newsletter -->\n");
      out.write("\n");
      out.write("\t<div class=\"newsletter\">\n");
      out.write("\t\t<div class=\"parallax_background parallax-window\" data-parallax=\"scroll\" data-image-src=\"images/newsletter.jpg\" data-speed=\"0.8\"></div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 offset-lg-2\">\n");
      out.write("\t\t\t\t\t<div class=\"newsletter_content text-center\">\n");
      out.write("\t\t\t\t\t\t<div class=\"newsletter_title_container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsletter_title\">subscribe to our newsletter</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsletter_subtitle\">we won't spam, we promise!</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"newsletter_form_container\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" id=\"newsletter_form\" class=\"newsletter_form\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" class=\"newsletter_input\" placeholder=\"your e-mail here\" required=\"required\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"newsletter_button\">submit</button>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Footer -->\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\">\n");
      out.write("\t\t<div class=\"footer_content\">\n");
      out.write("\t\t\t<div class=\"section_container\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<!-- About -->\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_about\">\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><div>a<span>star</span></div></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_about_text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam fringilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cards\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_1.jpg\" alt=\"\"></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_2.jpg\" alt=\"\"></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_3.jpg\" alt=\"\"></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_4.jpg\" alt=\"\"></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_5.jpg\" alt=\"\"></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Questions -->\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_questions\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">questions</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_list\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">About us</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Track Orders</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Returns</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Jobs</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Shipping</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Partners</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Bloggers</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Support</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Terms of Use</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Press</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Blog -->\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_blog\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">blog</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_blog_container\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Blog Item -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_item d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_image\"><a href=\"blog.html\"><img src=\"images/footer_blog_1.jpg\" alt=\"\"></a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_title\"><a href=\"blog.html\">what shoes to wear</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_date\">june 06, 2018</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_link\"><a href=\"blog.html\">Read More</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Blog Item -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_item d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_image\"><a href=\"blog.html\"><img src=\"images/footer_blog_2.jpg\" alt=\"\"></a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_title\"><a href=\"blog.html\">trends this year</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_date\">june 06, 2018</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_link\"><a href=\"blog.html\">Read More</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Contact -->\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_contact\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">contact</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_contact_list\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>C.</span><div>Your Company Ltd</div></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>A.</span><div>1481 Creekside Lane  Avila Beach, CA 93424, P.O. BOX 68</div></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>T.</span><div>+53 345 7953 32453</div></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>E.</span><div>office@youremail.com</div></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Social -->\n");
      out.write("\t\t<div class=\"footer_social\">\n");
      out.write("\t\t\t<div class=\"section_container\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_social_container d-flex flex-row align-items-center justify-content-between\">\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Instagram -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">instagram</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Google + -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">google +</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Pinterest -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">pinterest</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Facebook -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">facebook</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Twitter -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">twitter</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- YouTube -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-youtube\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">youtube</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Tumblr -->\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-tumblr-square\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">tumblr</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Credits -->\n");
      out.write("\t\t<div class=\"credits\">\n");
      out.write("\t\t\t<div class=\"section_container\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"credits_content d-flex flex-row align-items-center justify-content-end\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"credits_text\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/popper.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n");
      out.write("<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n");
      out.write("<script src=\"plugins/easing/easing.js\"></script>\n");
      out.write("<script src=\"plugins/parallax-js-master/parallax.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/isotope.pkgd.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/fitcolumns.js\"></script>\n");
      out.write("<script src=\"js/custom.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
