/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-03-21 04:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fashion.common.Formatter;
import com.fashion.model.domain.Paymethod;
import com.fashion.model.repository.PaymethodDAO;
import com.fashion.model.domain.Customer;
import java.util.List;
import com.fashion.model.domain.Topcategory;
import com.fashion.model.repository.TopcategoryDAO;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

PaymethodDAO payDAO=new PaymethodDAO(); 

	TopcategoryDAO topDAO=new TopcategoryDAO();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/inc/userinfo.jsp", Long.valueOf(1553059206918L));
    _jspx_dependants.put("/inc/sidebar.jsp", Long.valueOf(1553048074968L));
    _jspx_dependants.put("/inc/header.jsp", Long.valueOf(1552957629537L));
    _jspx_dependants.put("/inc/head.jsp", Long.valueOf(1552959256123L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.fashion.common.Formatter");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashion.model.domain.Customer");
    _jspx_imports_classes.add("com.fashion.model.repository.TopcategoryDAO");
    _jspx_imports_classes.add("com.fashion.model.repository.PaymethodDAO");
    _jspx_imports_classes.add("com.fashion.model.domain.Topcategory");
    _jspx_imports_classes.add("com.fashion.model.domain.Paymethod");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\n');

	String topcategory_id=request.getParameter("topcategory_id");
	//out.print("넘겨받은 상위 카테고리의 id값은 "+topcategory_id);
	
	//파라미터가 넘어오면, subcategory_id 값을 대체하자!!
	int subcategory_id=1;//기본값..
	if(request.getParameter("subcategory_id")!=null){//넘어오면...
		subcategory_id=Integer.parseInt(request.getParameter("subcategory_id"));
	}

      out.write('\n');
      out.write('\r');
      out.write('\n');

	String[] product_id=request.getParameterValues("product_id");
	String[] ea=request.getParameterValues("ea");
	for(int i=0;i<product_id.length;i++){
		System.out.println("product_id["+i+"]번째의 값은 "+product_id[i]+", ea["+i+"]번쨰의 값은 "+ea[i]);
	}
	int total=Integer.parseInt(request.getParameter("total"));
	List<Paymethod> paymethodList=payDAO.selectAll();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\n");
      out.write("<title>FashionShop</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\" content=\"aStar Fashion Template Project\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap-4.1.3/bootstrap.css\">\n");
      out.write("<link href=\"plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/categories.css\">\n");
      out.write("<script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/popper.js\"></script>\n");
      out.write("<script src=\"styles/bootstrap-4.1.3/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n");
      out.write("<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n");
      out.write("<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n");
      out.write("<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n");
      out.write("<script src=\"plugins/easing/easing.js\"></script>\n");
      out.write("<script src=\"plugins/parallax-js-master/parallax.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/isotope.pkgd.min.js\"></script>\n");
      out.write("<script src=\"plugins/Isotope/fitcolumns.js\"></script>\n");
      out.write("<script src=\"js/product.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/checkout.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/checkout_responsive.css\">\r\n");
      out.write("<script src=\"js/checkout.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function pay(){\r\n");
      out.write("\t//결제를 완료하고 결과 페이지 보여주기\r\n");
      out.write("\t$(\"form\").attr({\r\n");
      out.write("\t\t\"method\":\"post\",\r\n");
      out.write("\t\t\"action\":\"pay.jsp\"\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"form\").submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form>\r\n");
for(int i=0;i<product_id.length;i++){ 
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"product_id\" value=\"");
      out.print(product_id[i]);
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" name=\"ea\" value=\"");
      out.print(ea[i]);
      out.write("\" />\r\n");
} 
      out.write("\r\n");
      out.write("<div class=\"super_container\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\r\n");
      out.write("\t<header class=\"header\">\r\n");
      out.write("\t\t<div class=\"header_content d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Hamburger -->\r\n");
      out.write("\t\t\t<div class=\"hamburger menu_mm\"><i class=\"fa fa-bars menu_mm\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t<div class=\"header_logo\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><div>a<span>star</span></div></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t<nav class=\"header_nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\">home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">woman</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">man</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">lookbook</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header Extra -->\r\n");
      out.write("\t\t\t<div class=\"header_extra ml-auto d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Language -->\r\n");
      out.write("\t\t\t\t<div class=\"info_languages has_children\">\r\n");
      out.write("\t\t\t\t\t<div class=\"language_flag\"><img src=\"images/flag_1.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">english</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Language Dropdown Menu -->\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_2.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">french</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_3.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">japanese</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_4.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">russian</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_5.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown_text\">spanish</div>\r\n");
      out.write("\t\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Currency -->\r\n");
      out.write("\t\t\t\t<div class=\"info_currencies has_children\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">usd</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Currencies Dropdown Menu -->\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Cart -->\r\n");
      out.write("\t\t\t\t<div class=\"cart d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cart_icon\"><a href=\"cart.html\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/bag.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cart_num\">2</div>\r\n");
      out.write("\t\t\t\t\t</a></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"menu d-flex flex-column align-items-start justify-content-start menu_mm trans_400\">\r\n");
      out.write("\t\t<div class=\"menu_close_container\"><div class=\"menu_close\"><div></div><div></div></div></div>\r\n");
      out.write("\t\t<div class=\"menu_top d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Language -->\r\n");
      out.write("\t\t\t<div class=\"info_languages has_children\">\r\n");
      out.write("\t\t\t\t<div class=\"language_flag\"><img src=\"images/flag_1.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_text\">english</div>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Language Dropdown Menu -->\r\n");
      out.write("\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_2.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">french</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_3.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">japanese</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_4.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">russian</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\">\r\n");
      out.write("\t\t\t \t\t\t<div class=\"language_flag\"><img src=\"images/flag_5.svg\" alt=\"https://www.flaticon.com/authors/freepik\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_text\">spanish</div>\r\n");
      out.write("\t\t\t\t \t</a></li>\r\n");
      out.write("\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Currency -->\r\n");
      out.write("\t\t\t<div class=\"info_currencies has_children\">\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_text\">usd</div>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Currencies Dropdown Menu -->\r\n");
      out.write("\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\r\n");
      out.write("\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\r\n");
      out.write("\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"menu_search\">\r\n");
      out.write("\t\t\t\t<input type=\"search\" class=\"search_input menu_mm\" placeholder=\"Search\" required=\"required\">\r\n");
      out.write("\t\t\t\t<button class=\"header_search_button d-flex flex-column align-items-center justify-content-center menu_mm\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-search menu_mm\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav class=\"menu_nav\">\r\n");
      out.write("\t\t\t<ul class=\"menu_mm\">\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"index.html\">home</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">woman</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">man</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"#\">lookbook</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"blog.html\">blog</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu_mm\"><a href=\"contact.html\">contact</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"menu_extra\">\r\n");
      out.write("\t\t\t<div class=\"menu_social\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Info -->\r\n");
      out.write("\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t<div class=\"info_content d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	if (session.getAttribute("customer") != null) {

      out.write('\r');
      out.write('\n');

	Customer customer = (Customer) session.getAttribute("customer");

      out.write("\r\n");
      out.write("<div class=\"info_languages has_children\">\r\n");
      out.write("\t<div class=\"language_flag\"></div>\r\n");
      out.write("\t<div class=\"dropdown_text\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.print(customer.getName());
      out.write("님\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dropdown_arrow\">\r\n");
      out.write("\t\t<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">MyPage</div>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/member/logout.jsp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">Logout</div>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t<!-- Currency -->\r\n");
      out.write("\t\t\t\t<div class=\"info_currencies has_children\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_text\">usd</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_arrow\"><i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Currencies Dropdown Menu -->\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">EUR</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">YEN</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">GBP</div></a></li>\r\n");
      out.write("\t\t\t\t\t \t<li><a href=\"#\"><div class=\"dropdown_text\">CAD</div></a></li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Logo -->\r\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	List<Topcategory> topList=topDAO.selectAll();

      out.write("\n");
      out.write("<div class=\"sidebar_logo\">\n");
      out.write("\t<a href=\"/\"><div>a<span>Shop</span></div></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<nav class=\"sidebar_nav\">\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"index.jsp\">home<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t");
for(int i=0;i<topList.size();i++){
      out.write('\n');
      out.write('	');
      out.write('	');
Topcategory topcategory=topList.get(i); 
      out.write("\n");
      out.write("\t\t<li><a href=\"/category.jsp?topcategory_id=");
      out.print(topcategory.getTopcategory_id());
      out.write('"');
      out.write('>');
      out.print(topcategory.getTop_name());
      out.write("<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t");
}
      out.write("\n");
      out.write("\t\t<li><a href=\"#\">contact<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t<li><a href=\"/registForm.jsp\">Join us<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t</ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Search -->\r\n");
      out.write("\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"search_input\" placeholder=\"Search\" required=\"required\">\r\n");
      out.write("\t\t\t<button class=\"search_button\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Cart -->\r\n");
      out.write("\t\t<div class=\"cart d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t<div class=\"cart_icon\"><a href=\"cart.html\">\r\n");
      out.write("\t\t\t\t<img src=\"images/bag.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"cart_num\">2</div>\r\n");
      out.write("\t\t\t</a></div>\r\n");
      out.write("\t\t\t<div class=\"cart_text\">bag</div>\r\n");
      out.write("\t\t\t<div class=\"cart_price\">$39.99 (1)</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Home -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"home\">\r\n");
      out.write("\t\t<div class=\"parallax_background parallax-window\" data-parallax=\"scroll\" data-image-src=\"images/checkout.jpg\" data-speed=\"0.8\"></div>\r\n");
      out.write("\t\t<div class=\"home_container\">\r\n");
      out.write("\t\t\t<div class=\"home_content\">\r\n");
      out.write("\t\t\t\t<div class=\"home_title\">Checkout</div>\r\n");
      out.write("\t\t\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"cart.html\">Your Cart</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>Checkout</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Checkout -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"checkout\">\r\n");
      out.write("\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"checkout_container d-flex flex-xxl-row flex-column align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Billing -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"billing checkout_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"checkout_title\">무통장 결제 정보</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"checkout_form_container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- Name -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"checkout_name\">입금자명</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sender\" id=\"checkout_name\" class=\"checkout_input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Country -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"checkout_country\">은행 선택</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"bank\" id=\"checkout_country\" class=\"dropdown_item_select checkout_input\" require=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">우리은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">국민은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">NH농협은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">기업은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">신한은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Email -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"checkout_email\">Email Address*</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" id=\"checkout_email\" class=\"checkout_input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Cart Total -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cart_total\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart_total_inner checkout_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkout_title\">Cart total</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"cart_extra_total_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_title\">Subtotal</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_value ml-auto\">");
      out.print(Formatter.getCurrency(total) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"total_buy\" value=\"");
      out.print(total);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_title\">Shipping</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_value ml-auto\">Free</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_title\">Total</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cart_extra_total_value ml-auto\">");
      out.print(Formatter.getCurrency(total) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"total_pay\" value=\"");
      out.print(total);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Payment Options -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"payment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"payment_options\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
for(int i=0;i<paymethodList.size();i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
Paymethod paymethod=paymethodList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"payment_option clearfix\">");
      out.print(paymethod.getName() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"paymethod_id\" value=\"");
      out.print(paymethod.getPaymethod_id());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"checkmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Order Text -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"order_text\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra temp or so dales. Phasellus sagittis auctor gravida. Integ er bibendum sodales arcu id te mpus. Ut consectetur lacus.</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkout_button trans_200\"><a href=\"javascript:pay()\">결제 하기</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Newsletter -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"newsletter\">\r\n");
      out.write("\t\t<div class=\"parallax_background parallax-window\" data-parallax=\"scroll\" data-image-src=\"images/newsletter.jpg\" data-speed=\"0.8\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 offset-lg-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"newsletter_content text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"newsletter_title_container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsletter_title\">subscribe to our newsletter</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsletter_subtitle\">we won't spam, we promise!</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"newsletter_form_container\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer_content\">\r\n");
      out.write("\t\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- About -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_about\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><div>a<span>star</span></div></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_about_text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam fringilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cards\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_2.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_3.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_4.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/card_5.jpg\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Questions -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_questions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">questions</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Track Orders</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Returns</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Shipping</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Partners</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Bloggers</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Support</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Press</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Blog -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_blog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">blog</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_blog_container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Blog Item -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_item d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_image\"><a href=\"blog.html\"><img src=\"images/footer_blog_1.jpg\" alt=\"\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_title\"><a href=\"blog.html\">what shoes to wear</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_date\">june 06, 2018</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_link\"><a href=\"blog.html\">Read More</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Blog Item -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_item d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_image\"><a href=\"blog.html\"><img src=\"images/footer_blog_2.jpg\" alt=\"\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_title\"><a href=\"blog.html\">trends this year</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_date\">june 06, 2018</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"footer_blog_link\"><a href=\"blog.html\">Read More</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Contact -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xxl-3 col-md-6 footer_col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_title\">contact</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer_contact_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>C.</span><div>Your Company Ltd</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>A.</span><div>1481 Creekside Lane  Avila Beach, CA 93424, P.O. BOX 68</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>T.</span><div>+53 345 7953 32453</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-start justify-content-start\"><span>E.</span><div>office@youremail.com</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Social -->\r\n");
      out.write("\t\t<div class=\"footer_social\">\r\n");
      out.write("\t\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer_social_container d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Instagram -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">instagram</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Google + -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">google +</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Pinterest -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">pinterest</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Facebook -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">facebook</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Twitter -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">twitter</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- YouTube -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-youtube\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">youtube</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Tumblr -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"footer_social_item d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_icon\"><i class=\"fa fa-tumblr-square\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"footer_social_title\">tumblr</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Credits -->\r\n");
      out.write("\t\t<div class=\"credits\">\r\n");
      out.write("\t\t\t<div class=\"section_container\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"credits_content d-flex flex-row align-items-center justify-content-end\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"credits_text\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
